config/routes.rb
SMO::Application.routes.draw do  
  get "settings/index"

  resources :trial_expires
  resources :quickbooks
  resources :reports do
    collection do
      get :push_report_to_quickbook
    end

    member do
    post :send_mail
    get :job_report
    end    
  end
  resources :customs do
    collection do
      get :add_drop_values
      put :update_position
      get :get_dropdown_values
      get :edit_dropdown
      get :new_tab
      post :create_tab
      get :edit_table
      get :edit_table_heading
      post :create_table_fields
    end

    member do
      put :update_tab
      match :update_dropdown_values
      put :update_dropdown
      put :update_status
      put :update_table
      put :update_heading
      delete :delete_table
      match :update_customer_selection
    end
  end

  resources :customers
  resources :jobsites do
    member do
      get :ajax_show
      get :get_id
      get :show_jobsite
      get :get_jobsite
    end
  end

  resources :settings do
    collection do 
      get   :accounting
      match :authenticate
      match :oauth_callback
      match :dis_quickbooks
      match :bluedot
      get   :sync_customer_data
      get   :sync_items
      get   :sync_employees
      get   :sync_vendors
      get   :sync_salse_person
    end
  end

  resources :roles
  
  resources :contacts do
    member do
      get :ajax_show
    end
  end

  resources :jobs do
    member do
      get :job_pdf
      put :close_job
    end
    
    collection do
      get :my_jobs
    end

  end

  resources :items do
    collection do
      get :autocomplete_items
      get :create_inventory
    end
  end
 
  resources :documents 

  resources :inventories

  resources :jobtimes do
    collection do
      post :jobtime_shedule
    end
  end
  
  resources :notes
  devise_for :users

  resources :users

  match 'users/create' => "users#create",:as => :create_user

  get "dashboards/index"

  devise_for :companies, :controllers => {:sessions => 'sessions'}

  authenticated :company do
    root :to => "dashboards#index"
  end

  authenticated :user do
    root :to => "dashboards#index"
  end

  unauthenticated :user do
    devise_scope :user do
      post "api/users/sign_in", :to => "api/users_sessions#create"
      delete "api/users/sign_out", :to => "api/users_sessions#destroy"
      post "api/users/sign_up", :to => "api/registrations#users_create"
    end
  end
  
  unauthenticated :company do
    devise_scope :company do
      get "/" => "devise/sessions#new"
      post "api/sign_in", :to => "api/sessions#create"
      delete "api/sign_out", :to => "api/sessions#destroy"
      post "api/sign_up", :to => "api/registrations#create"
      get "sign_out", :to => "devise/sessions#destroy", :as => "logout"
    end
  end

  namespace :api do
    resources :customers
    resources :jobsites
    resources :notes
    resources :documents

    resources :items do
      collection do
        get :autocomplete_items
        get :create_inventory
      end
    end
    resources :inventories
    resources :jobtimes do
      collection do
        post :jobtime_shedule
      end
    end

    resources :dashboards
    resources :contacts 
    resources :jobs do
      member do
        put :close_job
      end
    end
    resources :customs do
      collection do
        post  :create_tab
      end
      member do
        put   :update_tab
        put   :update_dropdown_values
        put   :update_dropdown
        put   :update_status
      end
    end
  end
  

end

app/models/job.rb
class Job < ActiveRecord::Base
   
  has_attached_file :image
  attr_accessible :add_items, :assigned_to, :class_type, :due_date, :reference_no, :sales_person, :status, :sub_total, :summary, :job_number, :customer_id, :company_id, :contact_id, :jobsite_id, :name, :signature, :image
  # Data validations
  validates :reference_no, :class_type, :status, :assigned_to, :due_date, :sub_total, :presence => true
  validates :reference_no, :uniqueness => true
  #validates_numericality_of :sub_total, :greater_than => 0, :message => "must be greater than 0"
  #validates :sub_total, :format => { :with => /^[0-9]{1,5}((\.[0-9]{1,5})?)$/, :message => "should be a valid price less than 6 digit number" }
  validates :customer_id, :presence => true

  belongs_to :customer
  belongs_to :company
  has_many :notes, :as => :notable
  has_many :documents, :as => :documentable
  has_many :items
  has_many :jobtimes


  def self.search(search)
    if search
      where('reference_no ILIKE? OR status ILIKE? OR summary ILIKE?', "%#{search}%","%#{search}%","%#{search}%" )
    else
      scoped
    end
  end
  
  def self.total_on(date)
    where("status='open' AND date(created_at) = ?",date).count
  end

  def self.closed_jobs(date)
    where("status='closed' AND date(updated_at) = ?",date).count
  end

	def self.open_jobs(date)
   @job = Date.today-date
  end
end

app/controllers/api/jobs_controller.rb
class Api::JobsController < Api::BaseController
  before_filter :is_login?
  skip_before_filter :verify_authenticity_token

  # List of Jobs
  # curl -X GET -d 'api_key=E7tDAFxoiqneXMuhfpaq' http://localhost:3000/api/jobs.json
  def index
   if params[:my_job] == 'all jobs'
      @jobs = search_by_session(current_login.jobs.search(params[:search])).order("created_at desc").paginate(:per_page => 10, :page => params[:page])
    elsif params[:my_job]== 'unassigned jobs'
      @jobs = search_by_session(current_login.jobs.search(params[:search]).where(:assigned_to => "NULL")).paginate(:per_page => 10, :page => params[:page])
    elsif params[:my_job] == 'my jobs'
      @jobs = search_by_session(current_login.jobs.search(params[:search]).where("status='open' AND assigned_to != 'NULL'")).paginate(:per_page => 10, :page => params[:page])
    elsif params[:my_job] == 'closed jobs'
      @jobs = search_by_session(current_login.jobs.search(params[:search]).where(:status => "closed")).paginate(:per_page => 10, :page => params[:page])
    else
      @jobs = search_by_session(current_login.jobs.search(params[:search])).order("created_at desc").paginate(:per_page => 10, :page => params[:page])
    end

    respond_to do |format|
      format.xml {render :xml => @jobs}
      format.json {render :json => @jobs}
    end
  end

  # create jobs
  # curl -X POST -d 'job[reference_no]=XXXX&job[due_date(1i)]=year&job[due_date(2i)]=month&job[due_date(3i)]=day&job[due_date(4i)]=HH&job[due_date(5i)]=MM&job[class_type]=XXXX&job[assigned_to]=XXXX&job[status]=XXXX&job[sales_person]=XXXX&job[summary]=XXXX&job[contact_id]=XXXX&job[name]=XXXX&job[signature]=XXXX&job[customer_id]=XXXX&job[jobsite_id]=XXXX&api_key=E7tDAFxoiqneXMuhfpaq' http://localhost:3000/api/jobs.json
  def create
    @job = Job.new(params[:job])
    @job.company_id = current_company.id

    if @job.save
      response_message = {:message => "Job created successfully.", :job => @job}
    else
      response_message = {:message => "Job creation failed. Please try again!"}
    end

    respond_to do |format|
      format.xml { render :xml => response_message}
      format.json { render :json => response_message }
    end
  end

  # update jobs
  # curl -X PUT -d 'job[reference_no]=XXXX&job[due_date(1i)]=year&job[due_date(2i)]=month&job[due_date(3i)]=day&job[due_date(4i)]=HH&job[due_date(5i)]=MM&job[class_type]=XXXX&job[assigned_to]=XXXX&job[status]=XXXX&job[sales_person]=XXXX&job[summary]=XXXX&job[contact_id]=XXXX&job[name]=XXXX&job[signature]=XXXX&job[customer_id]=XXXX&job[jobsite_id]=XXXX&api_key=E7tDAFxoiqneXMuhfpaq' http://localhost:3000/api/jobs/id.json
  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(params[:job])
      response_message = {:message => "Job updated successfully.", :job => @job}
    else
      response_message = {:message => "Job updation failed. Please try again!"}
    end

    respond_to do |format|
      format.xml { render :xml => response_message }
      format.json { render :json => response_message }
    end
  end

  # delete jobs
  # curl -X DELETE -d 'api_key=E7tDAFxoiqneXMuhfpaq' http://localhost:3000/api/jobs/:id.json
  def destroy
    @job = Job.find(params[:id])
    if @job.destroy
      response_message = {:message => "Job deleted successfully.", :job => @job}
    else
      response_message = {:message => "Job deletion failed. Please try again!"}
    end

    respond_to do |format|
      format.xml { render :xml => response_message }
      format.json { render :json => response_message }
    end
  end

  # close the job (make the status of the job as closed accrding to id)
  # curl -X PUT -d 'api_key=E7tDAFxoiqneXMuhfpaq' http://localhost:3000/api/jobs/id/close_job.json
  def close_job
    @job = Job.find(params[:id])
    if @job.update_attribute(:status, "closed")
      response_message = {:message => "This job is closed successfully.", :job => @job}
    else
      response_message = {:message => "Failed to close this job. Please try again!"}
    end

    respond_to do |format|
      format.xml { render :xml => response_message }
      format.json { render :json => response_message }
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :is_login?
  before_filter :access_role?
  
  before_filter :session_types, :except => ["index", "show"]
  before_filter :find_id_by_role, :only => ["new", "edit", "create", "update"]

  def index
    if params[:my_job] == 'all jobs'
      @jobs = search_by_session(current_login.jobs.search(params[:search])).order("created_at desc").paginate(:per_page => 10, :page => params[:page])
    elsif params[:my_job]== 'unassigned jobs'
      @jobs = search_by_session(current_login.jobs.search(params[:search]).where(:assigned_to => "NULL")).paginate(:per_page => 10, :page => params[:page])
    elsif params[:my_job] == 'my jobs'
      @jobs = search_by_session(current_login.jobs.search(params[:search]).where("status='open' AND assigned_to != 'NULL'")).paginate(:per_page => 10, :page => params[:page])
    elsif params[:my_job] == 'closed jobs'
      @jobs = search_by_session(current_login.jobs.search(params[:search]).where(:status => "closed")).paginate(:per_page => 10, :page => params[:page])
    else
      @jobs = search_by_session(current_login.jobs.search(params[:search])).order("created_at desc").paginate(:per_page => 10, :page => params[:page])
    end
    if request.xhr?
      respond_to do |format|
        format.js 
      end
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def edit
    @job = Job.find(params[:id])
    @customer = Customer.find_by_id(@job.customer_id)
    @jobsite = Jobsite.find_by_id(@job.jobsite_id)
    session[:customer_id] = @job.customer_id
    session[:jobsite_id] = @job.jobsite_id
    session[:job_id] = @job.id
  end

  def create
    @job = Job.new(params[:job])
    @job.company_id = current_login.id
    @note = current_login.notes.new
    @notes = search_by_session_type("note",current_login.notes,"Job").order("created_at desc")
    if @job.save
      session_job_id
      if params[:select_action] == "print"
        redirect_to job_pdf_job_path(@job)
      elsif params[:select_action] == "email"
        @company = Company.find(current_login.id)
        CompanyMailer.send_job_details(@company,@job).deliver
        redirect_to jobs_path, :notice => "Job details are sent to company's email"
      else
        redirect_to jobs_path, :notice => 'Job was successfully created.'
      end
    else
      render :action => "new"
    end
  end

  def job_pdf
    @job = Job.find(params[:id])
    render :pdf => "jobs/job_pdf.html.erb"
  end

  def update
    @job = Job.find(params[:id])
    params[:job][:customer_id] = session[:customer_id]
    params[:job][:jobsite_id] = session[:jobsite_id]
    if @job.update_attributes(params[:job])
      session_job_id

      redirect_to jobs_path, :notice => "Job was successfully updated."
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @job = Job.find(params[:id])
    if @job.destroy
      #destroy the session
      session[:job_id] = nil
      flash[:notice] =  "Job was successfully deleted."
    else
      flash[:error] =  "Job deletion failed."
    end
    redirect_to jobs_url
  end

  def session_job_id
    @job.id ? session[:job_id] = @job.id : ''
  end

  def find_id_by_role
    @tech_role = current_login.roles.find_by_roll("Tech")
    @tech_role ? @tech_users = current_login.users.find_all_by_role_id(@tech_role.id) : @tech_users = nil

    @sales_role = current_login.roles.find_by_roll("Sales")
    @sales_role ? @sales_users = current_login.users.find_all_by_role_id(@sales_role.id) : @sales_users = nil
  end

  def close_job
    @jobs = search_by_session(current_login.jobs.search(params[:search])).order("created_at desc").paginate(:per_page => 10, :page => params[:page])
    @job = Job.find(params[:id])
    @job.update_attribute(:status, "closed")
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_all.html.erb
<div id ="my_job">
   <%= render :partial => 'my_jobs' %>
</div>

app/views/jobs/_display_customer_and_jobsite.html.erb
<div style="width:435px; font-weight: bold;" id="display_customer_and_jobsite">
  <p>
    <% if @customer == nil %>
      <span style="color:red">Please select customer for this job !</span><br/>
    <% else %>
      <%= link_to ("Customer : " + @customer.company_name + ", " + @customer.address1 + ", " + @customer.city + ", " + @customer.state + ", " + @customer.zip.to_s), edit_customer_path(@customer) %>
    <% end %>
  </p>

  <p>
    <% if @jobsite == nil %>
    <% else %>
      <%= link_to ("Job Site : " + @jobsite.name + ", " + @jobsite.city + ", " + @jobsite.state + ", " + @jobsite.zip), edit_jobsite_path(@jobsite) %>
    <% end %>
  </p>
</div>

app/views/jobs/_form.html.erb
<%= form_for(@job,:class => 'signature_form' ) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% @job.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= select_tag :select_action, options_for_select([['Actions', ' '], ['Convert to Invoice', 'convert_to_invoice'], ['Invoice & Pay', 'invoice_pay'], ['Email', 'email'], ['Print', 'print']], :selected => params[:select_action]) %>

  <%= f.hidden_field :customer_id, :value => @customer_id %>
  <%= f.hidden_field :jobsite_id, :value => @jobsite_id %>
  <%= f.hidden_field :company_id, :value => current_login.id %>
  <%= f.hidden_field :signature %>

  
  <div class="field">
    <%= f.label :reference_no %>
    <%= f.text_field :reference_no %>
  </div>
  <div class="field">
    <%= f.label :due_date %>
    <%= f.datetime_select :due_date, :class => "fix" %>
  </div>
  <div class="field">
    <%= f.label :class_type %>
    <%= f.select :class_type, options_for_select([["Installation", "installation"]],:selected => @job.class_type) %>
  </div>
  <div class="field">
    <%= f.label :assigned_to %>
    <%= f.select :assigned_to, options_for_select(["NULL"]+(@tech_users ? @tech_users.map{|user| [user.name]} : [""]), :selected => @job.assigned_to) %>
  </div>
  <div class="field">
    <%= f.label :status %>
    <%= f.select :status, options_for_select([["open"]]) %>
  </div>
  <div class="field">
    <%= label_tag :job_contact %>
    <% if current_login.contacts.empty? %>
      <span style="color: red;">NO CONTACTS</span>
    <% else %>
      <%= f.select :contact_id, options_for_select(search_by_session(current_login.contacts).map{|contact| [contact.name, contact.id]},:selected => @job.contact_id),{},:onchange => "GetContact(this)" %>
    <% end %>
    <div id="contact34">
    </div>
  </div>
  <div class="field">
    <%= f.label :sales_person %>
    <%= f.select :sales_person, options_for_select(@sales_users ? @sales_users.map{|user| [user.name]} : [""], :selected => @job.sales_person) %>
  </div>
  <div class="field">
    <%= f.label :summary %>
    <%= f.text_field :summary %>
  </div>
 
  <div class ="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <%=  f.label :signature %>
  <div id="canvas">
    <canvas class="roundCorners" id="newSignature" style="position: relative; margin: 0; padding: 0; border: 1px solid #c4caac;"><%= @job.signature %></canvas>
  </div>

  <div>
    <%= image_tag(@job.signature) %>
  </div>

  <script>
    $(document).ready(function(){
      signatureCapture();
    })
  </script>


  <div class="actions">
    <%= f.submit :class => "btn  btn-success",:onclick=>"signatureSave()" %>
  </div>

<% end %>

app/views/jobs/_jobs.html.erb
<%= form_for "form1" do |f|%>
  <% if params[:controller]=="customers" && (params[:action]=="new" || params[:action]=="index" ) %>

  <% elsif params[:controller]=="customers" && params[:action]=="edit"  %>
    Customer :
    <%= f.select :customers, options_for_select(["All"]+current_login.customers.map{|customer| [customer.company_name, customer.id]}, :selected => ( params[:cust_id] ? params[:cust_id] : session[:customer_id]) ), {}, :onchange => "getShowJobsite(this);" %>
  <% else %>
    Customer :
    <%= f.select :customers, options_for_select(["All"]+current_login.customers.map{|customer| [customer.company_name, customer.id]}, :selected => ( params[:cust_id] ? params[:cust_id] : session[:customer_id]) ), {}, :onchange => "getShowJobsite(this);" %>
  <% end %>

  <%= f.select :actions, options_for_select([["Actions", ""], ["Add Customer", new_customer_path],
      ["Add Job Site", new_jobsite_path] ,["Add Job", new_job_path] , ["Add Note", notes_path(:type => "Customer")], ["Add Contact", new_contact_path],
      ["Add Document", documents_path(:type => "Customer")]]) %>


  <br />
  <% if params[:controller]=="customers" && (params[:action]=="new" || params[:action]=="index") %>

  <% elsif params[:controller]=="jobsites" && (params[:action]=="index"  || params[:action]=="edit") %>

  <% else %>
    <div id="jobsite123">
      <% @jobsites = Jobsite.find_all_by_customer_id(session[:customer_id]) %>
      Job Site &nbsp; : <%= select_tag :jobsite_id, options_for_select(["None"]+["All"]+@jobsites.map{|job| [job.name,job.id]}, :selected => session[:jobsite_id]), :onchange => "getJobsitesId(this)" %>
    </div>
  <% end %>
<%  end %>


<p><span style = "color:#0044cc; font-weight: bold;"> Job # : <%= params[:controller] == "jobs" && params[:action] == "new" ? '' : session[:job_id] %>  </span></p>

<div id="display_customer_and_jobsite">
  <%= render :partial => 'display_customer_and_jobsite' %>
</div>


<script>
  $(document).ready(function() {
    $('#form1_actions').change(function() {
      location.href = $(this).val();
    });
  });
</script>

app/views/jobs/_my_jobs.html.erb
<table class="table">
  <table class="table table-striped">
    <tr>
      <th colspan="5">
        <%= link_to "Add New Job", new_job_path %>
      </th>
    </tr>
    <tr>
      <th>Reference no</th>
      <th>Date</th>
      <th>Status</th>
      <th>Summary</th>
      <th >Action</th>
    </tr>

    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to  job.reference_no, edit_job_path(job) %></td>
        <td><%= job.due_date %></td>
        <td><%= job.status %></td></div>
        <td><%= job.summary %></td>
        <td>
          <%= link_to "Delete", job, :method => :delete, :confirm => 'Are you sure?', :class => "btn btn-mini btn-danger" %>
          <%= job.status == 'closed' ? " " : (link_to "close",close_job_job_path(job), :method => :put, :remote => true, :class => "btn btn-mini btn-primary") %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td colspan="6">
        <%= will_paginate @jobs %>
      </td>
    </tr>
  </table>
</table>

 

app/views/jobs/_search.html.erb
<script>
  $(document).ready(function(){
    $('#search_actions').change(function(){
      location.href = $(this).val();
    });
  });
</script>

<%= form_for "search" do |f| %>

  <div style="margin-top: 10px;">
    Customer :
    <%= f.select :customer, :class => "span2", :id => "prependedInput", :placeholder => "customer" %>

    <!-- dropdown list for selecting different actions like : add job, add customer, add contact, etc -->
    Actions :
    <%= f.select :actions, options_for_select([["Actions", "#"], ["Add Customer", "#"],
    <div class="add-on" style="margin-left:20px;">Actions</div>
            ["Add Job Site", "new_jobsite_path"] ,["Add Job", "jobs/new"] , ["Add Note", "#"], ["Add Contact", "#"],
            ["Add Document", "new_document_path"]]), :placeholder => "Actions"
    %>

    <br />

    Job Site :
    <%= f.select :job_site, :class => "span2", :id => "prependedInput", :placeholder => "job site" %>

  </div>


<% end %>

app/views/jobs/close_job.js.erb
$("#jobs_all").html('<%= escape_javascript render :partial => 'all'%>');

app/views/jobs/edit.html.erb
<%= render '/layouts/timer' %>

<%= render :partial => 'jobs'  %>
<%= render :partial => '/layouts/tab_panel_for_job' %>
<%= render :partial => 'form' %>

app/views/jobs/index.html.erb
<%= render '/layouts/customer_with_action' %>
<%= render '/layouts/tab_panel_for_customer' %>


<%= form_tag :jobs, :method => 'get', :id => "jobs_search"  do  %>
<%= text_field_tag :search, params[:search], :placeholder => 'search',:class => "input-large search-query" %>
<%= submit_tag :Search, :class => "btn btn-mini btn-primary",:style => "width:60px; height:30px" %>  
&nbsp;
 <%= select_tag :my_job, options_for_select([["Select",""],['My Jobs','my jobs'],['Closed Jobs', 'closed jobs'],['Unassigned Jobs','unassigned jobs'],['All Jobs', 'all jobs']],params[:my_job]), {:onchange => "reload_with_new_param('my_job', this.value)"} %>

  <div id="jobs_all">
    <%= render :partial => 'all' %>
  </div>
<% end %>

app/views/jobs/index.js.erb
$("#jobs_all").html('<%= escape_javascript render :partial => 'all'%>');

app/views/jobs/job_pdf.html.erb
<div>
  <span style="font-size :18px; font-weight:bold;">Customer</span><br/>
  <% @job.customer_id ? customer = Customer.find(@job.customer_id) : '' %>
  <%=  customer.company_name  %><br/>
  <%=  customer.city %>,
  <%=  customer.state  %>,
  <%=  customer.zip %>
</div><br/>

<div>
  <span style="font-size :18px; font-weight:bold; border-bottom: 1px solid #CCC;">Job details</span><br/>

  <table class ="table table-hover">
    <tr>
      <td>Job Number</td>
      <td><%= @job.id %></td>
    </tr>

    <tr>
      <td>Reference Number</td>
      <td><%= @job.reference_no %></td>
    </tr>

    <tr>
      <td>Due_date</td>
      <td><%= @job.due_date %></td>
    </tr>

    <tr>
      <td>Class Type</td>
      <td><%= @job.class_type %></td>
    </tr>

    <tr>
      <td>Assigned_To</td>
      <td><%= @job.assigned_to %></td>
    </tr>

    <tr>
      <td>Status</td>
      <td><%= @job.status %></td>
    </tr>

    <tr>
      <td>Sales_person</td>
      <td><%= @job.sales_person %></td>
    </tr>
    <% if @job.contact_id.present? %>
      <tr>
        <td>Primary Contact</td>
        <td><%= current_login.contacts.find(@job.contact_id).name %></td>
      </tr>
    <% end %>
</table><br/>
</div>

<div style="float:right;width:500px;">
  <%= image_tag @job.signature, :width => "130px" %><br/>
  <%= @job.name %>
</div>

<style>
  table
    {
    border-collapse:collapse;
    }
  td, th, table{
    border: 1px solid black;
  }
</style>

app/views/jobs/new.html.erb
<%= render '/layouts/timer' %>

<%= render '/layouts/job_with_action' %>
<%= render '/layouts/tab_panel_for_job' %>
<%= render 'form' %>