config/routes.rb
SMO::Application.routes.draw do  
  get "settings/index"

  resources :trial_expires
  resources :quickbooks
  resources :reports do
    collection do
      get :push_report_to_quickbook
    end

    member do
    post :send_mail
    get :job_report
    end    
  end
  resources :customs do
    collection do
      get :add_drop_values
      put :update_position
      get :get_dropdown_values
      get :edit_dropdown
      get :new_tab
      post :create_tab
      get :edit_table
      get :edit_table_heading
      post :create_table_fields
    end

    member do
      put :update_tab
      match :update_dropdown_values
      put :update_dropdown
      put :update_status
      put :update_table
      put :update_heading
      delete :delete_table
      match :update_customer_selection
    end
  end

  resources :customers
  resources :jobsites do
    member do
      get :ajax_show
      get :get_id
      get :show_jobsite
      get :get_jobsite
    end
  end

  resources :settings do
    collection do 
      get   :accounting
      match :authenticate
      match :oauth_callback
      match :dis_quickbooks
      match :bluedot
      get   :sync_customer_data
      get   :sync_items
      get   :sync_employees
      get   :sync_vendors
      get   :sync_salse_person
    end
  end

  resources :roles
  
  resources :contacts do
    member do
      get :ajax_show
    end
  end

  resources :jobs do
    member do
      get :job_pdf
      put :close_job
    end
    
    collection do
      get :my_jobs
    end

  end

  resources :items do
    collection do
      get :autocomplete_items
      get :create_inventory
    end
  end
 
  resources :documents 

  resources :inventories

  resources :jobtimes do
    collection do
      post :jobtime_shedule
    end
  end
  
  resources :notes
  devise_for :users

  resources :users

  match 'users/create' => "users#create",:as => :create_user

  get "dashboards/index"

  devise_for :companies, :controllers => {:sessions => 'sessions'}

  authenticated :company do
    root :to => "dashboards#index"
  end

  authenticated :user do
    root :to => "dashboards#index"
  end

  unauthenticated :user do
    devise_scope :user do
      post "api/users/sign_in", :to => "api/users_sessions#create"
      delete "api/users/sign_out", :to => "api/users_sessions#destroy"
      post "api/users/sign_up", :to => "api/registrations#users_create"
    end
  end
  
  unauthenticated :company do
    devise_scope :company do
      get "/" => "devise/sessions#new"
      post "api/sign_in", :to => "api/sessions#create"
      delete "api/sign_out", :to => "api/sessions#destroy"
      post "api/sign_up", :to => "api/registrations#create"
      get "sign_out", :to => "devise/sessions#destroy", :as => "logout"
    end
  end

  namespace :api do
    resources :customers
    resources :jobsites
    resources :notes
    resources :documents

    resources :items do
      collection do
        get :autocomplete_items
        get :create_inventory
      end
    end
    resources :inventories
    resources :jobtimes do
      collection do
        post :jobtime_shedule
      end
    end

    resources :dashboards
    resources :contacts 
    resources :jobs do
      member do
        put :close_job
      end
    end
    resources :customs do
      collection do
        post  :create_tab
      end
      member do
        put   :update_tab
        put   :update_dropdown_values
        put   :update_dropdown
        put   :update_status
      end
    end
  end
  

end

app/models/custom.rb
class Custom < ActiveRecord::Base
  attr_accessible :field, :name, :company_id, :cus_type, :tab_id, :position, :status, :customer_id, :jobsite_id, :job_id

  belongs_to :company
  belongs_to :tab

  validates :name, :presence => true
  #validates :name, :uniqueness => {:scope => [:company_id, :cus_type, :tab_id], :message => "Custom field is already created"}
  
  has_many :dropdown_values, :dependent => :destroy
end

app/controllers/api/customs_controller.rb
class Api::CustomsController < Api::BaseController
  before_filter :is_login?
  skip_before_filter :verify_authenticity_token

  # list of custom fields
  # curl -X GET -d 'type=Customer/Job&tab=id&api_key=E7tDAFxoiqneXMuhfpaq' http://localhost:3000/api/customs.json
  def index
    if params[:type].present? && params[:type] =="Job"
      @default_tab = (params[:tab] ? params[:tab] : current_company.tabs.find_by_tab_type("Job").id)
    else
      @default_tab = (params[:tab] ? params[:tab] : current_company.tabs.first.id)
    end

    @tabs = current_company.tabs.where("tab_type=?", params[:type])
    @customs = current_company.customs.where("tab_id=? AND status=?", @default_tab, true).order('position asc')

    respond_to do |format|
      format.xml {render :xml => [@tabs, @customs]}
      format.json{render :json => [@tabs, @customs]}
    end
  end

  # create custom field for current tab
  # curl -X POST -d 'custom[name]=XXX&custom[field]=XXX&tab_name=XXX&drop_down_value=XXXX,XXXX,XXXX&type=Customer/Job&tab=id&api_key=E7tDAFxoiqneXMuhfpaq' http://localhost:3000/api/customs.json
  def create
    @tabs = current_company.tabs.order("created_at asc")
    @tab = current_company.tabs.find(params[:tab])

    @custom = current_company.customs.new(params[:custom])

    #all the custom fields matching the condition
    @customs = current_company.customs.where("tab_id=? AND status=?", params[:tab], true)

    #set the position of the custom element
    if !@customs.empty?
      @positions = @customs.map{|cus| cus.position}
      @custom.position = @positions.compact.sort.last+1
    else
      @custom.position = 1
    end

    #save the custom element
    @custom.tab_id = params[:tab]
    if @custom.save
      #update tab name
      @change_tab_name = current_login.tabs.find(params[:tab])
      @change_tab_name.update_attributes(:name => params[:tab_name])

      #save values for textbox, dropdown or calendar
      DropdownValue.create(:custom_id => @custom.id, :company_id => @custom.company_id, :drop_value => params[:drop_down_value])
      
      response_message = {:message => "All the tabs are loaded, custom fields matching search criteria are loaded, position for custom field set, Custom field created with it's value, Tab name updated.", :custom => @custom}
    else
      response_message = {:message => "Custom field creation failed. Please try again!"}
    end

    respond_to do |format|
      format.xml { render :xml => response_message }
      format.json { render :json => response_message }
    end
  end

  # update your label i.e. custom[name] 
  # curl -X PUT -d 'custom[name]=XXXX&api_key=E7tDAFxoiqneXMuhfpaq' http://localhost:3000/api/customs/id.json
  def update
    @custom = Custom.find(params[:id])

    if @custom.update_attributes(params[:custom])
      response_message = {:message => "Label for custom field updated successfully", :custom => @custom}
    else
      response_message = {:message => "Label updation failed. Please try again!"}
    end

    respond_to do |format|
      format.xml { render :xml => response_message }
      format.json { render :json => response_message }
    end
  end

  # update Text Box OR Calendar Values
  # curl -X PUT -d 'dropdown_value[drop_value]=XXXX&api_key=E7tDAFxoiqneXMuhfpaq' http://localhost:3000/api/customs/id/update_dropdown_values.json
  def update_dropdown_values
    @dropdown_value = current_login.dropdown_values.find(params[:id])
    if @dropdown_value.update_attributes(params[:dropdown_value])
      response_message = {:message => "Custom field value updated successfully", :dropdown_value => @dropdown_value}
    else
      response_message = {:message => "Custom field value updation failed. Please try again!"}
    end

    respond_to do |format|
      format.xml { render :xml => response_message }
      format.json { render :json => response_message }
    end
  end

  # update the values of dropdown list
  # curl -X PUT -d 'dropdown_value=XXXX, XXXX, XXXX&api_key=E7tDAFxoiqneXMuhfpaq' http://localhost:3000/api/customs/id/update_dropdown.json
  def update_dropdown
    @dropdown_value = current_company.dropdown_values.find(params[:id])

    if @dropdown_value.update_attribute(:drop_value, params[:dropdown_value])
      response_message = {:message => "Custom field Dropdown List values updated successfully.", :dropdown_values => @dropdown_value}
    else
      response_message = {:message => "Custom field Dropdown List values updation failed. Please try again!"}
    end

    respond_to do |format|
      format.xml { render :xml => response_message }
      format.json { render :json => response_message }
    end
  end

  # hide custom field  i.e. make status=false of the custom fields
  # curl -X PUT -d 'api_key=E7tDAFxoiqneXMuhfpaq' http://localhost:3000/api/customs/:id/update_status.json
  def update_status
    @custom = Custom.find(params[:id])

    if @custom.update_attribute(:status, false)
      response_message = {:message => "Custom field is made hidden", :custom => @custom}
    else
      response_message = {:message => "Custom field hiding failed. Please try again!"}
    end

    respond_to do |format|
      format.xml { render :xml => response_message }
      format.json { render :json => response_message }
    end
  end

  # delete custom field
  # curl -X DELETE -d 'api_key=E7tDAFxoiqneXMuhfpaq' http://localhost:3000/api/customs/:id.json
  def destroy
    @custom = Custom.find(params[:id])

    if @custom.destroy
      response_message = {:message => "Custom field deleted successfully.", :custom => @custom}
    else
      response_message = {:message => "Custom field deletion failed. Please try again!"}
    end

    respond_to do |format|
      format.xml { render :xml => response_message }
      format.json { render :xml => response_message }
    end
  end

  # create tabs for custom fields
  # curl -X POST -d 'tab[name]=XXXX&type=Customer/Job&api_key=E7tDAFxoiqneXMuhfpaq' http://localhost:3000/api/customs/create_tab.json
  def create_tab
    @tabs = current_login.tabs.where("tab_type=?", params[:type])
    @tab = current_company.tabs.new(params[:tab])
    @tab.tab_type = params[:type]

    if @tabs && @tabs.count >= 2
      response_message = {:message => "sorry cannot create more tabs"}
    else
      if @tab.save
        response_message = {:message => "Custom Tab created successfully", :tab => @tab}
      else
        response_message = {:message => "Custom Tab creation failed. Please try again!"}
      end
    end

    respond_to do |format|
      format.xml { render :xml => response_message }
      format.json { render :json => response_message }
    end
  end

  # update tabs name
  # curl -X PUT -d 'updated_name=XXXX&api_key=E7tDAFxoiqneXMuhfpaq' http://localhost:3000/api/customs/:id/update_tab.json
  def update_tab
    @tabs = current_login.tabs
    @tab = Tab.find(params[:id])

    if @tab.update_attribute(:name, params[:updated_name])
      response_message = {:message => "Custom tab name updated successfully.", :tab => @tab}
    else
      response_message = {:message => "Custom tab name updation failed. Please try again!"}
    end

    respond_to do |format|
      format.xml { render :xml => response_message }
      format.json { render :json => response_message }
    end
  end
end

app/helpers/customs_helper.rb
module CustomsHelper
end

app/views/customs/_all_tabs.html.erb
<%# Tabs available for both customer and jobs%>
<ul class="nav nav-tabs" id="custom_tab">
  <% @tabs.each do |tab| %>
    <li class=<%= (params[:tab].to_i == tab.id) ? 'active' : '' %> >
      <%= link_to (tab.name+" - #{tab.tab_type} "), new_custom_path(:tab => tab.id, :type => tab.tab_type) %>
    </li>
  <% end %>
    <li>
      <%= link_to "[+]New Tab", new_tab_customs_path(:type=> "Customer") %>
    </li>
</ul>

app/views/customs/_customs.html.erb
<script>
  $(function() {
    var fir_position;
    var sec_position;
    var cus_id;
    $( "ul.droptrue" ).sortable({
      connectWith: "ul",
      start: function(event, ui) {
        fir_position = ui.item.index()+1;
        cus_id = ui.item.attr('data-order');
      },
      stop: function(event, ui) {
        sec_position = ui.item.index()+1;
        $.ajax({
          url:"/customs/update_position",
          data:{
            pos_1:fir_position,
            pos_2:sec_position,
            id:cus_id,
            tab:<%= params[:tab] %>
          },
          type:'PUT',
          dataType:'script',
          success:function(data){}
        });
      }
    });
    $( "ul.dropfalse" ).sortable({
      connectWith: "ul",
      dropOnEmpty: false
    });
  });
</script>
<ul id="sortable" class="droptrue">
  <h5 style="margin-top:0px; background: #666; color: #FFF; padding:5px;">
    You can drag and drop the position of contents. Click on content (i.e. label / text) to edit that content
  </h5>
  <%=  customs.count==0 ? "No custom fields are created yet. Create your custom fields now!" : '' %>
  <% customs.each do |custom| %>
    <li class="ui-state-default" data-order="<%= custom.id %>" id="li<%= custom.id %>">
      <span id="label<%= custom.id %>">
        <%= label_tag custom.name, nil, :id=> "label#{custom.id}", :onclick => "inplace_edit(#{custom.id});" %>
      </span>
      <div id="custom_field_updation_<%= custom.id %>">
        <%= render :partial => 'customs/replace_dropdown',:locals => {:custom => custom} %>
      </div>
    </li>
  <% end %>
</ul>

<script>
  function show_edit_form(custom_id,value_id, tb_type){
    $.ajax({
      url:'/customs/get_dropdown_values',
      data:{
        custom_id:custom_id,
        dropdown_id:value_id,
        tab:<%= params[:tab] %>,
        type:tb_type
      },
      type:'GET',
      dataType:'script',
      success:function(data){}
    });
  }
</script>

app/views/customs/_edit_dropdowns.html.erb
<%= form_for @dropdown_values,:url => update_dropdown_custom_path(@custom_id), :method => 'PUT', :remote => true do |f| %>
  <small style="color:red">NOTE: Use commas(,) to seperate multiple values</small>
  <%= text_field_tag :dropdown_value, {}, :value => @dropdown_values, :class => "txt#{params[:cus_id]}", :style => 'width:418px; height:12px;' %><br/>
  <%= f.submit "update", :class => "btn btn-small btn-primary" %>
  <%= link_to_function 'Cancel', "cancelDropdownUpdate('#{params[:cus_id]}')", :class => "btn btn-mini btn-primary", :style => "color:white;" %>
<% end %>

<script>
  function cancelDropdownUpdate(id){
    $("#custom_field_updation_"+id).html('<%= escape_javascript render :partial => '/customs/replace_dropdown', :locals => {:custom => @custom} %>');
  }
</script>

app/views/customs/_update.html.erb
<%= form_for @custom,:url => custom_path(@custom), :method => 'PUT', :remote => true do |f| %>
  <%= f.text_field :name, :class => "txt#{@custom.id}", :style => 'width:200px;height:12px;' %><br/>
  <%= f.submit "update", :class => "btn btn-small btn-primary" %>
  <%= link_to_function 'cancel', "cancelUpdate('#{@custom.id}')", :class => "btn btn-mini btn-primary", :style => "color:white;" %>
<% end %>

<script>
  function cancelUpdate(id){
    $("#label"+id).html('<%= label_tag @custom.name, nil, :onclick => "inplace_edit(#{@custom.id}, 'label');" %>');
  }
</script>

app/views/customs/_update_table_heading.html.erb
<td><%= text_field_tag :fields_1, nil, :class => "small_row", :value => @values ? @values[0] : '', :placeholder => "value" %></td>
<td><%= text_field_tag :fields_2, nil, :class => "small_row", :value => @values ? @values[1] : '', :placeholder => "value" %></td>
<td><%= text_field_tag :fields_3, nil, :class => "mini_row", :value => @values ? @values[2] : '', :placeholder => "value" %></td>
<td><%= text_field_tag :fields_4, nil, :class => "mini_row", :value => @values ? @values[3] : '', :placeholder => "value" %></td>
<td><%= text_field_tag :fields_5, nil, :class => "mini_row", :value => @values ? @values[4] : '', :placeholder => "value" %></td>
<td><%= text_field_tag :fields_6, nil, :class => "mini_row", :value => @values ? @values[5] : '', :placeholder => "value" %></td>
<td><%= text_field_tag :fields_7, nil, :class => "mini_row", :value => @values ? @values[6] : '', :placeholder => "value" %></td>
<td><%= text_field_tag :fields_8, nil, :class => "mini_row", :value => @values ? @values[7] : '', :placeholder => "value", :placeholder => "value" %></td>
<td><%= text_field_tag :fields_9, nil, :class => "mini_row", :value => @values ? @values[8] : '', :placeholder => "value" %></td>
<td><%= text_field_tag :fields_10, nil, :class => "mini_row", :value => @values ? @values[9] : '', :placeholder => "value" %></td>
<td><%= text_field_tag :fields_11, nil, :class => "small_row", :value => @values ? @values[10] : '', :placeholder => "value" %></td>
<td colspan="2" style="width:50px">
  <% if @values %>
    <%= link_to_function "Update".html_safe, "update_heading_rows(#{@dropdown_value.id});", :class => "btn btn-mini btn-primary", :style => "color:white", :id => "update-btn" %>
  <% end %>
</td>


<script>
  function update_heading_rows(id) {
    var datas = new Array();
    for(var i=0; i<11; i++){
      value = document.getElementById("fields_"+(i+1)).value;
      value = (value==" " || value=="") ? "-" : value;
      datas[i] = value
    }
    fields = datas.join(",");
    $.ajax({
      url: '/customs/' + id + '/update_heading',
      data: {
        drop_value: fields
      },
      type: 'PUT',
      dataType: 'script',
      success: function(data) {
      }
    });
  }
</script>

app/views/customs/destroy.js.erb
$("#li<%= @custom.id %>").fadeOut();

app/views/customs/edit_table.js.erb
$("#display_table_fields").html('<%= escape_javascript render :partial => "customs/table_fields" %>');

app/views/customs/edit_table_heading.js.erb
$("#display_table_fields").html('<%= escape_javascript render :partial => "customs/update_table_heading" %>');

app/views/customs/new_tab.html.erb
<%= render '/layouts/tabs_for_settings' %>

<ul class="nav nav-tabs" id="custom_tab">
  <li class=<%= params[:controller]=="customs" && params[:action] == "new_tab" && params[:type]=="Customer" ? 'active' : '' %> >
    <%= link_to "Customer", new_tab_customs_path(:type=> "Customer") %>
  </li>

  <li class=<%= params[:controller]=="customs" && params[:action] == "new_tab" && params[:type]=="Job" ? 'active' : '' %> >
    <%= link_to "Job", new_tab_customs_path(:type=> "Job") %>
  </li>
</ul>

<table style="background: #F1F1F1">
  <%= form_for(@tab, :url => create_tab_customs_path(@tab, :type => params[:type]), :method => "POST") do |f| %>
    <% if @tab.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@tab.errors.count, "error") %> prohibited custom tabs from being saved:</h2>

        <ul>
          <% @tab.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :company_id, :value => current_login.id %>
    <%= f.hidden_field :tab_type, :value => params[:type] %>

    <tr style="background: #666; color: #FFF;">
      <td>
        Create Customer/Job tabs. You can only create two(2) tabs for customer and two(2) tabs for jobs.
      </td>
    </tr>

    <tr>
      <td>
        <%= "Create Customer/Job Tab first" %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.text_field :name, :placeholder => "Create your custom tabs" %>
      </td>
    </tr>

    <tr>
      <td>
        <%= f.submit "Save", :class => "btn btn-small btn-success", :style => "width:120px; height:30px;" %>
      </td>
    </tr>
    <tr>
      <td>
        &nbsp;
      </td>
    </tr>

  <% end %>
</table>

<table style="margin-top:10px;">
  <tr>
    <th style="background:#666; color: #FFF;">
      PREVIEW
    </th>
  </tr>
  <tr>
    <td style="background:#F1F1F1;">
<%# Tabs available for both customer and jobs%>
      <ul class="nav nav-tabs" id="custom_tab">
        <% @tabs.each do |tab| %>
          <li class="active" >
            <%= link_to (tab.name+" - #{tab.tab_type} "), "#" %>
          </li>
        <% end %>
      </ul>
    </td>
  </tr>
</table>

app/views/customs/update.js.erb
$("#label"+<%=@custom.id%>).html('<%= label_tag @custom.name, nil, :onclick => "inplace_edit(#{@custom.id}, 'label');" %>');

app/views/customs/update_dropdown_values.js.erb
$("#custom_field_updation_<%= @custom.id %>").html('<%= escape_javascript render :partial => 'customs/replace_dropdown',:locals => {:custom => @custom} %>');

app/views/customs/update_tab.js.erb
$("#allTabs").html("<%= escape_javascript render :partial => 'all_tabs' %>");

app/views/customs/update_table.js.erb
$("#create_table_fields").html('<%= escape_javascript render :partial => 'create_table_fields',:locals => {:custom => @custom} %>');