config/routes.rb
SMO::Application.routes.draw do  
  get "settings/index"

  resources :trial_expires
  resources :quickbooks
  resources :reports do
    collection do
      get :push_report_to_quickbook
    end

    member do
    post :send_mail
    get :job_report
    end    
  end
  resources :customs do
    collection do
      get :add_drop_values
      put :update_position
      get :get_dropdown_values
      get :edit_dropdown
      get :new_tab
      post :create_tab
      get :edit_table
      get :edit_table_heading
      post :create_table_fields
    end

    member do
      put :update_tab
      match :update_dropdown_values
      put :update_dropdown
      put :update_status
      put :update_table
      put :update_heading
      delete :delete_table
      match :update_customer_selection
    end
  end

  resources :customers
  resources :jobsites do
    member do
      get :ajax_show
      get :get_id
      get :show_jobsite
      get :get_jobsite
    end
  end

  resources :settings do
    collection do 
      get   :accounting
      match :authenticate
      match :oauth_callback
      match :dis_quickbooks
      match :bluedot
      get   :sync_customer_data
      get   :sync_items
      get   :sync_employees
      get   :sync_vendors
      get   :sync_salse_person
    end
  end

  resources :roles
  
  resources :contacts do
    member do
      get :ajax_show
    end
  end

  resources :jobs do
    member do
      get :job_pdf
      put :close_job
    end
    
    collection do
      get :my_jobs
    end

  end

  resources :items do
    collection do
      get :autocomplete_items
      get :create_inventory
    end
  end
 
  resources :documents 

  resources :inventories

  resources :jobtimes do
    collection do
      post :jobtime_shedule
    end
  end
  
  resources :notes
  devise_for :users

  resources :users

  match 'users/create' => "users#create",:as => :create_user

  get "dashboards/index"

  devise_for :companies, :controllers => {:sessions => 'sessions'}

  authenticated :company do
    root :to => "dashboards#index"
  end

  authenticated :user do
    root :to => "dashboards#index"
  end

  unauthenticated :user do
    devise_scope :user do
      post "api/users/sign_in", :to => "api/users_sessions#create"
      delete "api/users/sign_out", :to => "api/users_sessions#destroy"
      post "api/users/sign_up", :to => "api/registrations#users_create"
    end
  end
  
  unauthenticated :company do
    devise_scope :company do
      get "/" => "devise/sessions#new"
      post "api/sign_in", :to => "api/sessions#create"
      delete "api/sign_out", :to => "api/sessions#destroy"
      post "api/sign_up", :to => "api/registrations#create"
      get "sign_out", :to => "devise/sessions#destroy", :as => "logout"
    end
  end

  namespace :api do
    resources :customers
    resources :jobsites
    resources :notes
    resources :documents

    resources :items do
      collection do
        get :autocomplete_items
        get :create_inventory
      end
    end
    resources :inventories
    resources :jobtimes do
      collection do
        post :jobtime_shedule
      end
    end

    resources :dashboards
    resources :contacts 
    resources :jobs do
      member do
        put :close_job
      end
    end
    resources :customs do
      collection do
        post  :create_tab
      end
      member do
        put   :update_tab
        put   :update_dropdown_values
        put   :update_dropdown
        put   :update_status
      end
    end
  end
  

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :is_login?
  before_filter :access_role?
  
  def index
    
  end
  
  def accounting
    
  end
  
  def authenticate
    callback = oauth_callback_settings_url
    token = $qb_oauth_consumer.get_request_token(:oauth_callback => callback)
    session[:qb_request_token] = token
    redirect_to("https://appcenter.intuit.com/Connect/Begin?oauth_token=#{token.token}")
  end
  
  def oauth_callback
    at = session[:qb_request_token].get_access_token(:oauth_verifier => params[:oauth_verifier])
    access_token = at.token
    access_secret = at.secret
    realm_id = params['realmId']
    
    if signed_in?
      current_company.update_attributes({
          :access_token => access_token,
          :access_secret => access_secret,
          :realm_id => realm_id
        })
    end
    
    render 
  end
  
  def dis_quickbooks
    if signed_in?
      current_company.update_attributes({
          :access_token => nil,
          :access_secret => nil,
          :realm_id => nil
        })
      redirect_to accounting_settings_path
    end
  end
  
  def bluedot
    oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, current_company.access_token, current_company.access_secret)
    company_service = Quickeebooks::Online::Service::CompanyMetaData.new
    company_service.access_token = oauth_client
    company_service.realm_id = current_company.realm_id

    @company = company_service
    
  end

  # sync all customer from quickbook to SMO and vice versa
  def sync_customer_data
    oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, current_company.access_token, current_company.access_secret)

    customer_service = Quickeebooks::Online::Service::Customer.new
    customer_service.access_token = oauth_client
    customer_service.realm_id = current_company.realm_id

    #load all the customers created in quickbooks
    @customers =	customer_service.list.entries

    #check the condition for each customer either they exists in our application or not
    #if any of the customer doesnot exists in our application then create new customer
    #with quickbook customer values
    @customers.each do |customer|
      unless current_company.customers.exists?(:quickbook_customer_id => customer.id.to_i)
        current_company.customers.create(:types => "Customer", :account => " ", :company_name => customer.name, :address1 => customer.addresses.present? ? customer.addresses.first.line1 : "", :address2 => customer.addresses.present? ? customer.addresses.first.line2 : "", :city => customer.addresses.present? ? customer.addresses.first.city : "", :state => customer.addresses.present? ? customer.addresses.first.country_sub_division_code : "", :zip => customer.addresses.present? ? customer.addresses.first.postal_code : "", :phone => customer.phones.present? ? customer.phones.first.free_form_number : "", :website => customer.web_site.present? ? customer.web_site.uri : "", :quickbook_customer_id => customer.id)
      end
    end

    # push non-existing customers to QBO from SMO
    qbo_customers = []
    smo_customers = []
    non_matching_customers = []

    qbo_customers = @customers.map{|c| [c.name]}
    smo_customers = current_company.customers.where("types!=?", "Prospect").map{|c| [c.company_name]}

    non_matching_customers = smo_customers - qbo_customers # non matching in SMO, push these to quickbook

    non_matching_customers.each do |customer|
      smo_customers = current_company.customers.find_by_company_name(customer)
      push_to_quickbook(smo_customers)
    end
  end

  # push SMO_customer_to_quickbook
  def push_to_quickbook(customers)
    oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, current_company.access_token, current_company.access_secret)

    customer_service = Quickeebooks::Online::Service::Customer.new
    customer_service.access_token = oauth_client
    customer_service.realm_id = current_company.realm_id

    @customer = customers
    
    customer = Quickeebooks::Online::Model::Customer.new

    customer.name = @customer.company_name
    #customer.email = Quickeebooks::Online::Model::Email.new(@customer.email)

    address = Quickeebooks::Online::Model::Address.new
    address.line1 = @customer.address1
    address.line2 = @customer.address2
    address.city = @customer.city
    address.country_sub_division_code = @customer.state
    address.postal_code = @customer.zip
    customer.addresses = [address]

    phone1 = Quickeebooks::Online::Model::Phone.new
    phone1.device_type = "Primary"
    phone1.free_form_number = (@customer.phone.present? ? @customer.phone : "-")
    phone2 = Quickeebooks::Online::Model::Phone.new
    phone2.device_type = "Mobile"
    phone2.free_form_number = (@customer.phone.present? ? @customer.phone : "-")
    customer.phones = [phone1, phone2]

    website = Quickeebooks::Online::Model::WebSite.new
    website.uri = @customer.website
    customer.web_site = website

    #create customer with these datas
    customer_service.create(customer)

    filters = []
    filters << Quickeebooks::Online::Service::Filter.new(:text, :field => 'name', :value => customer.name)
    customer = customer_service.list(filters)
    @customer = current_company.customers.find(@customer.id)
    quickbook_customer_id = customer.entries.first.id

    #update quickbook_customer_id field in customer table
    @customer.update_attributes(:quickbook_customer_id => quickbook_customer_id)
  end


  

  # sync all items from quickbook
  def sync_items
    oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, current_company.access_token, current_company.access_secret)

    item_service = Quickeebooks::Online::Service::Item.new
    item_service.access_token = oauth_client
    item_service.realm_id = current_company.realm_id

    #load all the customers created in quickbooks
    @items =	item_service.list.entries

    @items.each do |item|
      if !current_company.items.exists?(:name => item.name)
        current_company.items.create(:quickbook_item_id => item.id, :name => item.name, :description => item.desc, :unit_price => item.unit_price.present? ? item.unit_price.amount : 0, :unit_cost => 0, :itemtype => "Quickbook", :qty => 1, :number => "-")
      else
        @item = current_company.items.find_by_name(item.name)
        @item.update_attributes(:quickbook_item_id => item.id, :name => item.name, :description => item.desc, :unit_price => item.unit_price.present? ? item.unit_price.amount : 0, :unit_cost => 0, :itemtype => "Quickbook", :qty => 1, :number => "-")
      end
    end
  end



  def sync_employees
    oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, current_company.access_token, current_company.access_secret)

    user_service = Quickeebooks::Online::Service::Employee.new
    user_service.access_token = oauth_client
    user_service.realm_id = current_company.realm_id

    # find sub-contractor role
    @role_id = current_company.roles.find_by_roll("Tech").id if current_company.roles.exists?(:roll => "Tech")

    # load all the employees
    @employees = user_service.list.entries

    # check for existing value
    @employees.each do |employee|
      unless current_company.users.exists?(:name => employee.name, :role_id => @role_id)
        #email = (employee.email.present? ? employee.email.address : "#{SecureRandom.urlsafe_base64 + "@gmail.com"}")
        email = employee.email.present? ? employee.email.address : "-"
        @user = current_company.users.new(:password => "qawsed!@#", :password_confirmation => "qawsed!@#", :role_id => @role_id, :name => employee.name, :accounting_name => employee.name, :email => email, :smo_user => false, :language => "English", :company_id => current_company.id, :time_zone => "Hawaii", :accounting_type => "Employee")
        @user.save(:validate => false)
      end
    end
  end



  def sync_vendors
    oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, current_login.access_token, current_login.access_secret)

    vendor_service = Quickeebooks::Online::Service::Vendor.new
    vendor_service.access_token = oauth_client
    vendor_service.realm_id = current_login.realm_id

    # find sub-contractor role
    @role_id = current_login.roles.find_by_roll("Subcontractor").id if current_login.roles.exists?(:roll => "Subcontractor")

    # load all the employees
    @vendors = vendor_service.list.entries

    # check for existing value
    @vendors.each do |vendor|
      unless current_login.users.exists?(:name => vendor.name, :role_id => @role_id)
        #email = (vendor.email.present? ? vendor.email.address : "#{SecureRandom.urlsafe_base64 + "@gmail.com"}") # if email present
        email = vendor.email.present? ? vendor.email.address : "-"
        @user = current_login.users.new(:password => "qawsed!@#", :password_confirmation => "qawsed!@#", :role_id => @role_id, :name => vendor.name, :accounting_name => vendor.name, :email => email, :smo_user => false, :language => "English", :company_id => current_login.id, :time_zone => "Hawaii", :accounting_type => "Vendor")
        @user.save(:validate => false)
      end
    end
  end



  def sync_salse_person
    # sync Rep
    oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, current_login.access_token, current_login.access_secret)

    rep_service = Quickeebooks::Online::Service::Rep.new
    rep_service.access_token = oauth_client
    rep_service.realm_id = current_login.realm_id

    # find sub-contractor role
    @role_id = current_login.roles.find_by_roll("Sales").id if current_login.roles.exists?(:roll => "Sales")

    # load all the employees
    @sales_persons = user_service.list.entries

    # check for existing value
    @sales_persons.each do |sales_person|
      unless current_login.users.exists?(:name => sales_person.name, :role_id => @role_id)
        email = (sales_person.email.present? ? sales_person.email.address : "#{SecureRandom.urlsafe_base64 + "@gmail.com"}")

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/accounting.html.erb
<style>
  .notice{
    color: green;
    background: #F1F1F1;
    box-shadow: 2px 2px 2px 2px #999;
    padding: 10px;
    margin-left:20px;
    font-weight: bold;
  }
  #items{
    width: 100%;
    margin: 10px;
    padding: 5px;
  }
  .button{
    width: 156px;
  }
</style>
<%= render :partial => "layouts/tabs_for_settings" %>
  <!-- somewhere in your document include the Javascript -->
  <script type="text/javascript" src="https://appcenter.intuit.com/Content/IA/intuit.ipp.anywhere.js"></script>

  <!-- configure the Intuit object: 'grantUrl' is a URL in your application which kicks off the flow, see below -->
  <script>
    intuit.ipp.anywhere.setup({menuProxy: '<%= bluedot_settings_url %>', grantUrl: "<%= authenticate_settings_url %>"});
  </script>
  
<% if !current_login.access_token.present? && !current_login.access_secret.present? && !current_login.realm_id.present? %>
  <!-- this will display a button that the user clicks to start the flow -->
  <ipp:connectToIntuit></ipp:connectToIntuit>
<% else %>
  <ipp:blueDot></ipp:blueDot>
  <div id="items">
    <%= button_to "Disconnect from Quickbooks", {:controller => "settings", :action => "dis_quickbooks"} , :class => "btn btn-small btn-primary"%>
  </div>

  <div id="items">
    <%= link_to_function "Sync Customer Now", "sync_customer_data();", :class => "btn btn-small btn-primary button", :id => "sync_customer" %>
    <span id="notice-customer" class="notice">Import all new customers created on quickbooks.</span>
  </div>

  <div id="items">
    <%= link_to_function "Sync Items Now", "sync_items();", :id => "sync_items", :class => "btn btn-small btn-primary button" %>
    <span id="notice-item" class="notice">Import all Items created on quickbooks.</span>
  </div>

  <div id="items">
    <%= link_to_function "Sync Employees Now", "sync_employees();", :id => "sync_employee", :class => "btn btn-small btn-primary button" %>
    <span id="notice-employee" class="notice">Import all employees created on quickbooks.</span>
  </div>

  <div id="items">
    <%= link_to_function "Sync Vendors Now", "sync_vendors();", :id => "sync_vendor", :class => "btn btn-small btn-primary button" %>
    <span id="notice-vendor" class="notice">Import all vendors created on quickbooks.</span>
  </div>

  <div id="items" style="display:none;">
    <%= link_to_function "Sync Sales Person Now", "sync_salse_person();", :id => "sync_sales_person", :class => "btn btn-small btn-primary button" %>
    <span id="notice-user" class="notice">Import all sales representative created on quickbooks.</span>
  </div>
<% end %>

<script>
  function sync_customer_data(){
    document.getElementById("sync_customer").innerHTML = "Synchronizing...."
    $.ajax({
      url: '/settings/sync_customer_data',
      type: 'GET',
      dataType: 'script',
      success: function(data){}
    });
  }

  function sync_items(){
    document.getElementById("sync_items").innerHTML = "Synchronizing....";
    $.ajax({
      url: '/settings/sync_items',
      type: 'GET',
      dataType: 'script',
      success: function(data){}
    })
  }

  //sync all users
  function sync_employees(){
    document.getElementById("sync_employee").innerHTML = "Synchronizing....";
    $.ajax({
      url: '/settings/sync_employees',
      type: 'GET',
      dataType: 'script',
      success: function(data){}
    })
  }

  //sync all sub-contractors
  function sync_vendors(){
    document.getElementById("sync_vendor").innerHTML = "Synchronizing....";
    $.ajax({
      url: '/settings/sync_vendors',
      type: 'GET',
      dataType: 'script',
      success: function(data){}
    })
  }

  //sync all vendors
  function sync_salse_person(){
    
  }
</script>

app/views/settings/bluedot.js.erb
<%= @company.registered_company_name %>

app/views/settings/index.html.erb
<%= render :partial => "layouts/tabs_for_settings" %>

app/views/settings/oauth_callback.html.erb
<script type="text/javascript">
  window.opener.location.reload(true);self.close();
</script>

app/views/settings/sync_customer_data.js.erb
$("#notice-customer").html("All the customers are successfully sync to H5SW Application. Please Confirm it!");
setTimeout(function(){
  $("#notice-customer").hide();
  $("#notice-customer").fadeIn();
  $("#notice-customer").html("Import all new customers created on quickbook.");
}, 8000);
$("#sync_customer").html("Sync Customer Now")
$("#notice-customer").hide();
$("#notice-customer").fadeIn();

app/views/settings/sync_employees.js.erb
$("#notice-employee").html("All the employees are successfully sync to H5SW Application. Please Confirm it!");
setTimeout(function(){
  $("#notice-employee").hide();
  $("#notice-employee").fadeIn();
  $("#notice-employee").html("Import all employees created on quickbooks.");
}, 8000);
$("#sync_employee").html("Sync Employees Now")
$("#notice-employee").hide();
$("#notice-employee").fadeIn();

app/views/settings/sync_items.js.erb
$("#notice-item").html("Items are successfully imported from quickbook. Please Confirm it!");
setTimeout(function(){
  $("#notice-item").hide();
  $("#notice-item").fadeIn();
  $("#notice-item").html("Import all Items created on quickbooks.");
}, 8000);
$("#notice-item").hide();
$("#notice-item").fadeIn();
$("#sync_items").html("Sync Items Now");

app/views/settings/sync_vendors.js.erb
$("#notice-vendor").html("All the vendors are successfully sync to H5SW Application. Please Confirm it!");
setTimeout(function(){
  $("#notice-vendor").hide();
  $("#notice-vendor").fadeIn();
  $("#notice-vendor").html("Import all new vendors created on quickbook.");
}, 8000);
$("#sync_vendor").html("Sync Vendors Now")
$("#notice-vendor").hide();
$("#notice-vendor").fadeIn();