config/routes.rb
SMO::Application.routes.draw do  
  get "settings/index"

  resources :trial_expires
  resources :quickbooks
  resources :reports do
    collection do
      get :push_report_to_quickbook
    end

    member do
    post :send_mail
    get :job_report
    end    
  end
  resources :customs do
    collection do
      get :add_drop_values
      put :update_position
      get :get_dropdown_values
      get :edit_dropdown
      get :new_tab
      post :create_tab
      get :edit_table
      get :edit_table_heading
      post :create_table_fields
    end

    member do
      put :update_tab
      match :update_dropdown_values
      put :update_dropdown
      put :update_status
      put :update_table
      put :update_heading
      delete :delete_table
      match :update_customer_selection
    end
  end

  resources :customers
  resources :jobsites do
    member do
      get :ajax_show
      get :get_id
      get :show_jobsite
      get :get_jobsite
    end
  end

  resources :settings do
    collection do 
      get   :accounting
      match :authenticate
      match :oauth_callback
      match :dis_quickbooks
      match :bluedot
      get   :sync_customer_data
      get   :sync_items
      get   :sync_employees
      get   :sync_vendors
      get   :sync_salse_person
    end
  end

  resources :roles
  
  resources :contacts do
    member do
      get :ajax_show
    end
  end

  resources :jobs do
    member do
      get :job_pdf
      put :close_job
    end
    
    collection do
      get :my_jobs
    end

  end

  resources :items do
    collection do
      get :autocomplete_items
      get :create_inventory
    end
  end
 
  resources :documents 

  resources :inventories

  resources :jobtimes do
    collection do
      post :jobtime_shedule
    end
  end
  
  resources :notes
  devise_for :users

  resources :users

  match 'users/create' => "users#create",:as => :create_user

  get "dashboards/index"

  devise_for :companies, :controllers => {:sessions => 'sessions'}

  authenticated :company do
    root :to => "dashboards#index"
  end

  authenticated :user do
    root :to => "dashboards#index"
  end

  unauthenticated :user do
    devise_scope :user do
      post "api/users/sign_in", :to => "api/users_sessions#create"
      delete "api/users/sign_out", :to => "api/users_sessions#destroy"
      post "api/users/sign_up", :to => "api/registrations#users_create"
    end
  end
  
  unauthenticated :company do
    devise_scope :company do
      get "/" => "devise/sessions#new"
      post "api/sign_in", :to => "api/sessions#create"
      delete "api/sign_out", :to => "api/sessions#destroy"
      post "api/sign_up", :to => "api/registrations#create"
      get "sign_out", :to => "devise/sessions#destroy", :as => "logout"
    end
  end

  namespace :api do
    resources :customers
    resources :jobsites
    resources :notes
    resources :documents

    resources :items do
      collection do
        get :autocomplete_items
        get :create_inventory
      end
    end
    resources :inventories
    resources :jobtimes do
      collection do
        post :jobtime_shedule
      end
    end

    resources :dashboards
    resources :contacts 
    resources :jobs do
      member do
        put :close_job
      end
    end
    resources :customs do
      collection do
        post  :create_tab
      end
      member do
        put   :update_tab
        put   :update_dropdown_values
        put   :update_dropdown
        put   :update_status
      end
    end
  end
  

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @jobs = current_login.jobs.paginate(:per_page => 10, :page => params[:page])
  end
  
  def show
    @job = Job.find(params[:id])
  end

  def push_report_to_quickbook
    oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, current_login.access_token, current_login.access_secret)
    
    invoice_service = Quickeebooks::Online::Service::Invoice.new
    invoice_service.access_token = oauth_client
    invoice_service.realm_id = current_login.realm_id

    customer_service = Quickeebooks::Online::Service::Customer.new
    customer_service.access_token = oauth_client
    customer_service.realm_id = current_login.realm_id

    @job = current_login.jobs.find(params[:id])
    @customer = current_login.customers.find(@job.customer_id)

    invoice = Quickeebooks::Online::Model::Invoice.new

    if current_login.inventories.exists?(:job_id => @job.id) || current_login.jobtimes.exists?(:job_id => @job.id)

      # created_at and updated_at
      meta_data = Quickeebooks::Online::Model::MetaData.new
      meta_data.create_time = @job.created_at
      meta_data.last_updated_time = @job.updated_at
      invoice.meta_data = meta_data

      # create header parts
      header = Quickeebooks::Online::Model::InvoiceHeader.new
      header.msg = @job.summary
      # find the customer in quickbook
      customer = customer_service.fetch_by_id(@customer.quickbook_customer_id)
      if customer.present?
        header.customer_id = customer.id
        header.customer_name = customer.name
      end
    
      # header.sub_total_amount = @job.sub_total
      header.to_be_printed = true
      header.to_be_emailed = true
      header.bill_email = current_login.email
      header.due_date = @job.due_date
      invoice.header = header

      @items = current_login.inventories.where("job_id = ?", @job.id)
      if @items.present?
        @items.each do |item|
          line_item = Quickeebooks::Online::Model::InvoiceLineItem.new
          if item.description.present?
            line_item.desc = item.description
          else
            line_item.desc = item.name
          end
          # line_items.item_id = Item.find(@job.item_id).quickbook_item_id
          line_item.unit_price = item.unit_price
          line_item.quantity = item.qty.to_f
          line_item.amount = (item.unit_price.to_f * item.qty.to_f)     # unit_price * qty

          # push each line items in invoice line_items
          invoice.line_items << line_item
        end
      end

      @items = current_login.jobtimes.where("job_id =?", @job.id)
      if @items.present?
        @items.each do |item|
          line_item = Quickeebooks::Online::Model::InvoiceLineItem.new
          
          hrs = item.qty.split(":")[0]
          min = item.qty.split(":")[1]
          sec = item.qty.split(":")[2]
          
          qty = hrs.to_f + min.to_f/60 + sec.to_f/3600
          line_item.quantity = qty
          line_item.unit_price = item.price.to_f/qty

          # display service item name in description
          service_item = Item.find(item.service)
          line_item.desc = service_item.name

          if item.billable == true
            line_item.amount = item.price
          end

          invoice.line_items << line_item
        end
      end

      invoice_service.create(invoice)
    end
  end
  
	  def send_mail
		@job = Job.find(params[:id])
		@company = Company.find(current_login.id)
		CompanyMailer.send_job_report(@company,@job).deliver
		respond_to do |format|
		  format.js
		end
	  end
	  
	  def job_report
		 @job = Job.find(params[:id])
		 render :pdf => "reports/job_report.html.erb"
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
<%= render :partial => 'layouts/tab_panel_for_dashboards' %>
<table class="table">
  <table class="table table-striped">
    <tr>
    </tr>
    <tr>
      <th>Reference no</th>
      <th>Date</th>
      <th>Status</th>
      <th>Summary</th>
    </tr>

    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to (job.reference_no), report_path(job.id) %></td>
        <td><%= job.due_date %></td>
        <td><%= job.status %></td></div>
        <td><%= job.summary %></td>
      </tr>
    <% end %>
      <tr>
        <td colspan="4">
        <%= will_paginate @jobs %>
      </td>
      </tr>
  </table>
</table>

 

app/views/reports/job_report.html.erb
<div id ="job_report">

<div id="company">
<%= @job.company.name %><br/>
<%= @job.company.email %>
</div>
  
<div style="float:right;">
  <span style="font-weight:bold; font-size:18px;float:right;">Invoice</span><br/>
    <table style="width:300px;">
      <tr>
        <th>Date</th>
        <th>Invoice.No</th>
      </tr>
      
      <tr>
        <td><%= Date.today %></td>
        <td></td>
      </tr>
      
      <tr>
        <th style="border:none;"></th>
        <th>Due Date</th>
      </tr>
      
      <tr>
        <td style="border:none;"></td>
        <td><%= @job.due_date %></td>
      </tr>
    </table>
</div><br/>
  
  <div id="billto">
    <table>
      <tr><th style="background-color:grey;"><span style="font-weight: bold; font-size:14px;text-align:left;">Bill To</span></th></tr>
      <tr>
        <td><%= @job.customer.company_name %>,<br/>
            <%= @job.customer.address1 %>,<br/>
            <%= @job.customer.address2 %>,<br/>
            <%= @job.customer.city %>,<%= @job.customer.state %>,<%= @job.customer.zip %>
        </td>
      </tr>
    </table>
  </div><br/>
  

<div style="float:right;">
  <table>
    <tr>
      <th>Amount Due</th>
      <th>Enclosed</th>
    </tr>
    
    <tr>
      <td></td>
      <td>&nbsp;</td>
    </tr>
  </table><br/>
</div><br/><br/>

<div>
  <table id="totals" style="width:100%;">
      <tr>
        <th style="background-color:grey;">Activity</th>
        <th style="background-color:grey">Amount</th>
      </tr>
  <% Inventory.exists?(:job_id => @job.id) ? inventory = Inventory.find_all_by_job_id(@job.id) : ""  %>
  <% if inventory.present? %>
    
      <% inventory.each do |inventory| %>
      <tr>
        <td><%= inventory.description %></td>
        <td class="inv"><%= inventory.unit_price.to_f * inventory.qty.to_f %></td>
      </tr>
      <% end %>
      <%  else %>
      <% end %>

      <% Jobtime.exists?(:job_id => @job.id) ? jobtime = Jobtime.find_all_by_job_id(@job.id) : "" %>
        <% if jobtime.present? %>
      

      <% jobtime.each do |jobtime| %>
      <tr>
        <td><%= jobtime.timetype %></td>
        <td class="inv"><%= jobtime.price %></td>
      </tr>
      <% end %>
      <% else %>
      <% end %>
  </table><br/>
</div>

<div>
  <% Note.exists?(:notable_id => @job.id) ? note = Note.where(:note_type => 'Service Request').find_all_by_notable_id(@job.id) : "" %>
  <% if note.present? %>
  <p style="font-weight: bold; font-size: 20px;">Notes</p>
    <table style="width:300px;">
      <tr>
        <th>Service Request Notes</th>
      </tr>
      <% note.each do |note| %>
        <tr>
          <td>* <%= note.description %></td>
        </tr>
      <% end %>
    </table><br/>
  <% else %>
  <% end %>
  
    <% Note.exists?(:notable_id => @job.id) ? note = Note.where(:note_type => 'Service Request').find_all_by_notable_id(@job.id) : "" %>
    <% if note.present? %>
    <table style="width:300px;">
      <tr>
        <th>Service Performed Notes</th>
      </tr>
        <% note.each do |note| %>
        <tr>
          <td>* <%= note.description %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
  <% end %>
  </table>
</div>
</div>

<style>
  table
    {
    border-collapse:collapse;
    }
  td, th, table{
    border: 1px solid black;
  }
</style>
 
 <script type="text/javascript">
  var tds = document.getElementById('totals').getElementsByTagName('td');
  var sum = 0;
  for(var i = 0; i < tds.length; i ++) {    
    if(tds[i].className == 'inv') {
      sum += isNaN(tds[i].innerHTML) ? 0 : parseFloat(tds[i].innerHTML);
    }
  }
  document.getElementById('totals').innerHTML += '<tr style="background-color:grey;font-weight:bold;"><td>Total</td><td>$' + sum + '</td></tr>';
 </script>

app/views/reports/push_report_to_quickbook.js.erb
<% if current_login.inventories.exists?(:job_id => @job.id) || current_login.jobtimes.exists?(:job_id => @job.id) %>
  alert("Report is pushed to quickbook invoice. Please make sure of it");
<% else %>
  alert("At least one item is required to generate invoice. Please create items for this job");
<% end %>

app/views/reports/show.html.erb
<div style="margin-bottom: 10px; font-weight: bold; font-size: 40px;text-align: center; font-family: Times new roman;">Report</div><br/>
<div id="customer">
  <span style="font-size :18px; font-weight:bold;">Customer</span><br/>
  <% @job.customer_id ? customer = Customer.find(@job.customer_id) : '' %>
  <%= customer ? customer.company_name : '-' %><br/>
  <%= customer ? customer.city : '-' %>,
  <%= customer ? customer.state : '-' %>,
  <%= customer ? customer.zip : '-' %>
</div><br/>

<% if @job.jobsite_id.present? && @job.jobsite_id != 0 %>
  <% jobsite = Jobsite.find(@job.jobsite_id) %>
  <div id="jobsites">
    <span style="font-size :20px; font-weight:bold;">Jobsite</span><br/>
    <%= jobsite.name %><br/>
    <%= jobsite.city %>,
    <%= jobsite.state %>,
    <%= jobsite.zip %>
  </div>
<% end %>
<br/>

<div>
  <% if current_login.notes.exists?(:notable_id => params[:id], :note_type => 'Service Request') %>
    <p style="font-weight: bold; font-size: 20px;">Notes</p>
    <% note = current_login.notes.where("notable_id = ? AND note_type =?", params[:id], 'Service Request') %>
    <table class ="table table-striped">
      <tr>

        <th>Service Request Notes</th>
      </tr>
      <% note.each do |note| %>
        <tr>
          <td>* <%= note.description %></td>
        </tr>
      <% end %>
    </table>
  <% end %>


  <% if  current_login.notes.exists?(:notable_id => params[:id], :note_type => 'Service Performed') %>
    <% note = current_login.notes.where("notable_id = ? AND note_type =?", params[:id], 'Service Performed') %>
    <table class ="table table-striped">
      <tr>
        <th>Service Performed Notes</th>
      </tr>
      <% note.each do |note| %>
        <tr>
          <td>* <%= note.description %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>
<br/>
<div>
  <% Inventory.exists?(:job_id => @job.id) ? inventory = Inventory.find_all_by_job_id(@job.id) : "" %>
  <% if inventory.present? %>
    <p style="font-weight: bold; font-size: 20px;">Items List</p>
    <table  class="table table-striped">
      <tr>
        <th>Type</th>
        <th>Item Name</th>
        <th>Quantity</th>
        <th>Description</th>
        <th>Number</th>

      </tr>
      <% inventory.each do |inventory| %>
        <tr>
          <td><%= inventory.itemtype %></td>
          <td><%= inventory.name %></td>
          <td><%= inventory.qty %></td>
          <td><%= inventory.description %></td>
          <td><%= inventory.number %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
  <% end %>
</div>

<div>
  <% Jobtime.exists?(:job_id => @job.id) ? jobtime = Jobtime.find_all_by_job_id(@job.id) : "" %>
  <% if jobtime.present? %>
    <p style="font-weight: bold; font-size: 20px;">Time</p>
    <table  class ="table table-striped">
      <tr>
        <th>Type</th>
        <th>Date</th>
        <th>Quantity</th>
        <th>who</th>
        <th>Service</th>
      </tr>
      <% jobtime.each do |jobtime| %>
        <tr>
          <td><%= jobtime.timetype %></td>
          <td><%= jobtime.start_time %></td>
          <td><%= jobtime.qty %></td>
          <td><%= jobtime.user %></td>
          <td><%= jobtime.service != nil ? Item.find(jobtime.service).name : '' %></td>
        </tr>
      <% end %>
    </table>
  <% else %>
  <% end %>
</div>  

<div style="width:100%; text-align: right;">
  <%= link_to "print", job_report_report_path(@job.id), :class => "btn btn-small btn-primary"%>
  <%= link_to_function "Email",:class => "btn btn-small btn-primary", :method => :post, :onclick => "mail(#{@job.id});" %>
  <%= link_to_function "Push To Quickbook Invoice","send_to_quickbook(#{params[:id]});", :class => "btn btn-small btn-primary" %>
  <%= link_to "Back", reports_path(@job.id),:class => "btn btn-small btn-primary" %>
</div>

<script>
  function send_to_quickbook(id){
    $.ajax({
      url: '/reports/push_report_to_quickbook',
      data: {
        id: id
      },
      type: 'GET',
      dataType: 'script',
      success: function(data) {
      }
    });  
  }
</script>